name: Python CI

on:
  push:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.10', '3.14']
    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Enable Long Paths (Windows Only)
        if: matrix.os == 'windows-latest'
        run: git config --system core.longpaths true
      - name: Initialize Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          uv venv
          uv pip install pytest
          uv pip install -e .
      - name: Run Unit Tests
        run: uv run pytest -s

  sympy-earliest:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Initialize Python 3.7
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: '3.7'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install "nrpy @ git+https://github.com/nrpy/nrpy.git" "sympy==1.9" pytest
          python -m pip install -e .
      - name: Run Unit Tests
        run: pytest -s

  sympy-dev:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.14']
    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Initialize Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          uv venv
          uv pip install "sympy @ git+https://github.com/sympy/sympy.git" pytest
          uv pip install -e .
      - name: Run Unit Tests
        run: uv run pytest -s
