name: Python CI

on: [push]

jobs:
  pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3']
    steps:
      - name: Checkout Repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install Package Manager
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          enable-cache: true
      - name: Initialize Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}
      - name: Install Python Dependencies
        run: uv sync
      - name: Run Unit Tests
        run: uv run pytest -s

  sympy_earliest-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install Package Manager
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          enable-cache: true
      - name: Initialize Python 3.6.7
        run: uv python install 3.6.7
      - name: Install Python Dependencies
        run: uv sync --with "sympy==1.9"
      - name: Run Unit Tests
        run: uv run --python 3.6.7 pytest -s nrpylatex/tests/test_parse_latex.py

  sympy_development-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install Package Manager
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          enable-cache: true
      - name: Initialize Python 3
        run: uv python install 3
      - name: Install Python Dependencies
        run: uv sync --with "sympy @ git+https://github.com/sympy/sympy.git"
      - name: Run Unit Tests
        run: uv run pytest -s
