name: CI
on: [push]
jobs:
  sympy_stable-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: echo "checking out branch ${{ github.ref }} on ${{ github.repository }}."
      - name: checkout repository
        uses: actions/checkout@v2
      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: install sympy (latest stable version)
        run: python -m pip install ipython sympy
      - name: perform unit testing
        run: python -m unittest
  sympy_stable-windows:
    runs-on: windows-latest
    steps:
      - run: echo "checking out branch ${{ github.ref }} on ${{ github.repository }}."
      - name: checkout repository
        uses: actions/checkout@v2
      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: install sympy (latest stable version)
        run: python -m pip install ipython sympy
      - name: perform unit testing
        run: python -m unittest
  sympy_stable-macos:
    runs-on: macos-latest
    steps:
      - run: echo "checking out branch ${{ github.ref }} on ${{ github.repository }}."
      - name: checkout repository
        uses: actions/checkout@v2
      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: install sympy (latest stable version)
        run: python -m pip install ipython sympy
      - name: perform unit testing
        run: python -m unittest
  sympy_earliest-ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "checking out branch ${{ github.ref }} on ${{ github.repository }}."
      - name: checkout repository
        uses: actions/checkout@v2
      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: 3.6
      - name: install sympy (earliest supported version)
        run: python -m pip install ipython sympy==1.2
      - name: perform unit testing
        run: python -m unittest nrpylatex.tests.test_parse_latex
  sympy_development-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: echo "checking out branch ${{ github.ref }} on ${{ github.repository }}."
      - name: checkout repository
        uses: actions/checkout@v2
      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: install ipython
        run: python -m pip install ipython
      - name: install sympy (latest development version)
        run: python -m pip install -U git+https://github.com/sympy/sympy/
      - name: perform unit testing
        run: python -m unittest
  test_nrpytutorial-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: echo "checking out branch ${{ github.ref }} on ${{ github.repository }}."
      - name: checkout repository
        uses: actions/checkout@v2
      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: install sympy (latest stable version)
        run: python -m pip install ipython sympy
      - name: clone nrpytutorial repository
        run: git clone https://github.com/zachetienne/nrpytutorial.git
      - name: install nrpylatex from GitHub
        run: python -m pip install git+https://github.com/zachetienne/nrpylatex.git
      - name: change directory and perform unit testing
        run: cd nrpytutorial && python -m unittest tests.test_parse_BSSN
